/**
 * PatronsPanel — "Tonight at the hearth" / "TONIGHT'S PATRONS".
 *
 * Renders the recurring presences from the world layer. Each row
 * is a patron title (heading) and their dialogue line (mood).
 * The structure mirrors the existing `AmbientPanel`; the data
 * source is different — `WorldNight.patrons` is generated by the
 * world layer per day, where AmbientPanel's lines are static
 * theme tier-keyed flavour.
 *
 * Pure presentational. No state. Theme-agnostic — the parent
 * resolves the section label + patrons from
 * `generateNightlyWorld()`.
 *
 * See: docs/workout-rpg/020-world-state-and-patrons.md
 */

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import type { PatronPresence } from '../../world';
import {
  workoutColors,
  workoutRadii,
  workoutSpacing,
  workoutType,
} from '../../theme/workoutColors';

export interface PatronsPanelProps {
  sectionLabel: string;
  patrons: readonly PatronPresence[];
  testID?: string;
}

export function PatronsPanel({
  sectionLabel,
  patrons,
  testID,
}: PatronsPanelProps): JSX.Element {
  return (
    <View testID={testID} style={styles.card}>
      <Text testID="patrons-section-label" style={styles.section}>
        {sectionLabel}
      </Text>
      <View style={styles.list}>
        {patrons.map((p, i) => (
          <View
            key={`${p.patron.id}-${i}`}
            testID={`patron-row-${p.patron.id}`}
            style={styles.row}
          >
            <Text style={styles.title} numberOfLines={1}>
              {p.patron.title}
            </Text>
            <Text style={styles.line} numberOfLines={2}>
              {p.line}
            </Text>
          </View>
        ))}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: workoutColors.surface,
    borderRadius: workoutRadii.lg,
    borderWidth: 1,
    borderColor: workoutColors.border,
    padding: workoutSpacing.md,
    gap: workoutSpacing.sm,
  },
  section: {
    ...workoutType.caption,
    letterSpacing: 2,
    color: workoutColors.textMuted,
  },
  list: {
    gap: workoutSpacing.sm,
  },
  row: {
    gap: 2,
  },
  title: {
    ...workoutType.body,
    color: workoutColors.textPrimary,
  },
  line: {
    ...workoutType.caption,
    color: workoutColors.textSecondary,
    fontStyle: 'italic',
  },
});
