/**
 * Supabase-side items table. Phase 1 of automatic sync.
 *
 * Two operations:
 *   - upsertItems: push a batch of local rows up. Keyed on the row's
 *     `id` (Supabase UUID); on conflict we update the existing row in
 *     place. Returns the canonical server timestamps so the caller can
 *     stamp `remote_updated_at` locally.
 *   - listItemsForHouseholdSince: pull every row in the household that
 *     was updated after the given cursor. First call passes `null`
 *     (full backfill). Tombstones (deleted_at IS NOT NULL) are
 *     included so the local store can mirror soft deletes.
 *
 * Logging contract: NEVER log user content. The narrow log lines here
 * include counts and the household id prefix only.
 */

import { getSupabaseClient } from '../supabaseClient';

export interface RemoteItem {
  id: string;
  householdId: string;
  localId: string | null;
  name: string;
  normalizedName: string | null;
  category: string | null;
  barcode: string | null;
  createdByMemberId: string | null;
  createdByDeviceId: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

export interface RemoteItemUpsertInput {
  /** UUID. Pre-generated by the caller for new rows. */
  id: string;
  householdId: string;
  localId: string | null;
  name: string;
  normalizedName: string | null;
  category: string | null;
  barcode: string | null;
  createdByMemberId: string | null;
  createdByDeviceId: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

export interface RemoteResult<T = void> {
  ok: boolean;
  message: string;
  data?: T;
}

interface ItemRow {
  id: string;
  household_id: string;
  local_id: string | null;
  name: string;
  normalized_name: string | null;
  category: string | null;
  barcode: string | null;
  photo_uri: string | null;
  notes: string | null;
  quantity: number | null;
  unit: string | null;
  confidence: number | null;
  created_by_member_id: string | null;
  created_by_device_id: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

function rowToRemote(row: ItemRow): RemoteItem {
  return {
    id: row.id,
    householdId: row.household_id,
    localId: row.local_id,
    name: row.name,
    normalizedName: row.normalized_name,
    category: row.category,
    barcode: row.barcode,
    createdByMemberId: row.created_by_member_id,
    createdByDeviceId: row.created_by_device_id,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at,
  };
}

function shortHh(id: string): string {
  return id.length > 8 ? `${id.slice(0, 8)}…` : id;
}

function unconfigured<T = void>(): RemoteResult<T> {
  return { ok: false, message: 'Supabase is not configured.' };
}

export async function upsertItems(
  inputs: RemoteItemUpsertInput[],
): Promise<RemoteResult<RemoteItem[]>> {
  const client = getSupabaseClient();
  if (!client) return unconfigured<RemoteItem[]>();
  if (inputs.length === 0) {
    return { ok: true, message: 'Nothing to push.', data: [] };
  }
  const rows = inputs.map(input => ({
    id: input.id,
    household_id: input.householdId,
    local_id: input.localId,
    name: input.name,
    normalized_name: input.normalizedName,
    category: input.category,
    barcode: input.barcode,
    created_by_member_id: input.createdByMemberId,
    created_by_device_id: input.createdByDeviceId,
    created_at: input.createdAt,
    updated_at: input.updatedAt,
    deleted_at: input.deletedAt,
  }));
  const { data, error } = await client
    .from('items')
    .upsert(rows, { onConflict: 'id' })
    .select('*')
    .returns<ItemRow[]>();
  if (error) {
    console.warn(
      `[dwhi.sync] items upsert failed (${rows.length} row${rows.length === 1 ? '' : 's'}): ${error.message}`,
    );
    return { ok: false, message: error.message };
  }
  console.log(`[dwhi.sync] items upsert ok (${data.length} row${data.length === 1 ? '' : 's'})`);
  return { ok: true, message: 'ok', data: data.map(rowToRemote) };
}

export async function listItemsForHouseholdSince(
  remoteHouseholdId: string,
  since: string | null,
): Promise<RemoteResult<RemoteItem[]>> {
  const client = getSupabaseClient();
  if (!client) return unconfigured<RemoteItem[]>();
  let q = client
    .from('items')
    .select('*')
    .eq('household_id', remoteHouseholdId)
    .order('updated_at', { ascending: true });
  if (since) q = q.gt('updated_at', since);
  const { data, error } = await q.returns<ItemRow[]>();
  if (error) {
    console.warn(
      `[dwhi.sync] items pull failed for ${shortHh(remoteHouseholdId)}: ${error.message}`,
    );
    return { ok: false, message: error.message };
  }
  console.log(
    `[dwhi.sync] items pulled ${data.length} for ${shortHh(remoteHouseholdId)}` +
      (since ? ` (since ${since})` : ' (full)'),
  );
  return { ok: true, message: 'ok', data: data.map(rowToRemote) };
}
